# kalamine keyboard layout descriptor
name        = "glostis-colemak"
name8       = "glostis-colemak"
locale      = "us"
variant     = "hack"
author      = "glostis"
description = "Custom Colemak layout adapted for coding and writing in French"
url         = "https://OneDeadKey.github.com/kalamine"
version     = "0.0.1"
geometry    = "ERGO"

base = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃ _   ┆ +   ┆
┆ `   ┃ 1   │ 2   │ 3   │ 4   │ 5   ┃ 6   │ 7   │ 8   │ 9   │ 0 ° ┃ -   ┆ =   ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ Q   │ W   │ F   │ J   │ B   ┃ Y   │ U   │ I   │ O   │ P   ┃ {   ┆ }   ┆
·     ┃   œ │     │   à │   ù │     ┃     │   û │   î │   ô │     ┃ [   ┆ ]   ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃ A   │ R   │ S   │ T   │ G   ┃ H   │ N   │ E   │ L   │     ┃ "   ┆ |   ┆
·     ┃   â │   é │   è │     │   – ┃   ( │   ) │   ê │     │** : ┃ '   ┆ \   ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆ >   ┃ Z   │ X   │ C   │ D _ │ V   ┃ K   │ M   │ ;   │ !   │ ?   ┃           ·
┆ <   ┃     │     │   ç │   _ │   — ┃   « │   » │ ,   │ . … │ /   ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''

altgr = '''
╭╌╌╌╌╌┰─────┬─────┬─────┬─────┬─────┰─────┬─────┬─────┬─────┬─────┰╌╌╌╌╌┬╌╌╌╌╌╮
┆     ┃   ¹ │   ² │   ³ │   ⁴ │   ⁵ ┃   ⁶ │   ⁷ │   ⁸ │   ⁹ │   ⁰ ┃     ┆     ┆
┆     ┃   ₁ │   ₂ │   ₃ │   ₄ │   ₅ ┃   ₆ │   ₇ │   ₈ │   ₉ │   ₀ ┃     ┆     ┆
╰╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │   × │     │     ┃     ┆     ┆
·     ┃   @ │   < │   > │   $ │   % ┃   ^ │   & │   * │     │     ┃     ┆     ┆
·     ┠─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┼╌╌╌╌╌┤
·     ┃     │     │     │     │     ┃     │     │     │     │     ┃     ┆     ┆
·     ┃   { │   ( │   ) │   } │     ┃     │     │     │     │     ┃     ┆     ┆
╭╌╌╌╌╌╂─────┼─────┼─────┼─────┼─────╂─────┼─────┼─────┼─────┼─────╂╌╌╌╌╌┴╌╌╌╌╌╯
┆     ┃     │     │     │     │     ┃     │     │     │     │     ┃           ·
┆     ┃   ~ │   [ │   ] │     │   # ┃     │     │     │     │     ┃           ·
╰╌╌╌╌╌┸─────┴─────┴─────┴─────┴─────┸─────┴─────┴─────┴─────┴─────┚ · · · · · ·
'''
